### ISSUE TITLE
Unneeded health check created for kube-system:default-http-backend service 

### ISSUE THREAD

**Issue by tomoe** [kubernetes/ingress-gce#385]
When I create an Ingress that has default backends, the controller still creates a GCE healthcheck pointing to kube-system:default-http-backend service (default 404 server) even thought there's no chance of hitting the pod. 

Usually, that doesn't do any harm, but possibly duplicated healthcheck probes may overload the l7-default-backend pod and causes the pod to restart with error messages because the resource setting for the container is very small (cpu: 10m, memory: 20M). 

Now I think: 
- it would be nice if HC gets created if it really is needed
- (not an issue of the controller, but) l7-default-backend resource setting may need to be increased, autoscalable, and/or configurable.

**Comment by rramkumar1** [comment]
@tomoe This issue should be fixed in GLBC v1.2.0. We will only create a backends service for the system default backend if the user does not specify a default backend in their Ingress.

**Comment by albertodominguezs** [comment]
I still get that default BE. I even remove it manually and it forces the creation / link again.

**Comment by rramkumar1** [comment]
@albertodominguezs What GKE cluster version are you using?

**Comment by albertodominguezs** [comment]
@rramkumar1 **Cluster Version:** 1.13.6-gke.5

**Comment by rramkumar1** [comment]
@albertodominguezs Ok, would be useful to see your Ingress YAML so please file a separate issue. Thanks!
