### ISSUE TITLE
Ingress Healthcheck Configuration

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#42]
_From @freehan on May 15, 2017 21:25_

On GCE, ingress controller sets up default healthcheck for backends. The healthcheck will point to the nodeport of backend services on every node. Currently, there is no way to describe detail configuration of healthcheck in ingress. On the other side, each application may want to handle healthcheck differently. To bypass this limitation, on Ingress creation, ingress controller will scan all backend pods and pick the first ReadinessProbe it encounters and configure healthcheck accordingly. However, healthcheck will not be updated if ReadinessProbe was updated. (Refer: https://github.com/kubernetes/ingress/issues/582)

I see 3 options going forward with healthcheck

1) Expand the Ingress or Service spec to include more configuration for healthcheck. It should include the capabilities provided by major cloud providers, GCP, AWS...

2) Keep using readiness probe for healthcheck configuration, 
            a) Keep today's behavior and communicate clearly regarding the expectation. However, this still breaks the abstraction and declarative nature of k8s. 
            b) Let ingress controller watch the backend pods for any updates for ReadinessProbe. This seems expensive and complicated. 
 
3) Only setup default healthcheck for ingresses. Ingress controller will only ensure the healthcheck exist periodically, but do not care about its detail configuration. User can configure it directly thru the cloud provider.  

I am in favor of option 3). There are always more bells and whistles on different cloud providers. The higher layer we go, the more features we can utilize. For L7 LB, there is no clean simple way to describe every intention. So is the case for health check. To ensure a smooth experience, k8s still sets up the basics. For advance use cases, user will have to configure it thru the cloud provider. 

Thoughts? @kubernetes/sig-network-misc 

_Copied from original issue: kubernetes/ingress-nginx#720_

**Comment by bowei** [comment]
_From @k8s-ci-robot on May 15, 2017 21:25_

@freehan: These labels do not exist in this repository: `sig/network`.

<details>

In response to [this](https://github.com/kubernetes/ingress/issues/720):

>On GCE, ingress controller sets up default healthcheck for backends. The healthcheck will point to the nodeport of backend services on every node. Currently, there is no way to describe detail configuration of healthcheck in ingress. On the other side, each application may want to handle healthcheck differently. To bypass this limitation, on Ingress creation, ingress controller will scan all backend pods and pick the first ReadinessProbe it encounters and configure healthcheck accordingly. However, healthcheck will not be updated if ReadinessProbe was updated. (Refer: https://github.com/kubernetes/ingress/issues/582)
>
>I see 3 options going forward with healthcheck
>
>1) Expand the Ingress or Service spec to include more configuration for healthcheck. It should include the capabilities provided by major cloud providers, GCP, AWS...
>
>2) Keep using readiness probe for healthcheck configuration, 
>            a) Keep today's behavior and communicate clearly regarding the expectation. However, this still breaks the abstraction and declarative nature of k8s. 
>            b) Let ingress controller watch the backend pods for any updates for ReadinessProbe. This seems expensive and complicated. 
> 
>3) Only setup default healthcheck for ingresses. Ingress controller will only ensure the healthcheck exist periodically, but do not care about its detail configuration. User can configure it directly thru the cloud provider.  
>
>
>I am in favor of option 3). There are always more bells and whistles on different cloud providers. The higher layer we go, the more features we can utilize. For L7 LB, there is no clean simple way to describe every intention. So is the case for health check. To ensure a smooth experience, k8s still sets up the basics. For advance use cases, user will have to configure it thru the cloud provider. 
>
>Thoughts? @kubernetes/sig-network-misc 

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>

**Comment by bowei** [comment]
_From @tonglil on August 14, 2017 20:8_

For option 3, is the "default healthcheck" hitting the "default-backend"?

**Comment by edevil** [comment]
I'm in favor of option 1.

I'm sure there is a minimum subset of features common to all cloud providers that make sense to be included in the ingress spec, and it would improve the current situation a lot.

**Comment by tobsch** [comment]
+1

**Comment by tonglil** [comment]
For those in favor of option 1, please read this conversation: https://github.com/kubernetes/ingress-gce/issues/28.

**Comment by hdave** [comment]
Reading that conversation -- I think configuring healthcheck via annotations would be great.

**Comment by jeremywadsack** [comment]
@bowei I think that kubernetes/contrib#325 is related to this?

**Comment by hdave** [comment]
I would be in favor of option #1 if the ingress controller could configure an HTTPS health check to a back end services that uses a cert.  If not, I would go with option #3 and just let our devops team manually tweak the health check without the ingress controller caring and resetting it back.

**Comment by matti** [comment]
"on Ingress creation, ingress controller will scan all backend pods and pick the first ReadinessProbe it encounters and configure healthcheck accordingly"

I'm not seeing this, the health check will always point to default path "/" with:

```
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
```

**Comment by Gogoro** [comment]
I got the same issue as @matti. When I create an `ingress` pointing to a `service`, which again points to a `pod` it just keeps hitting `/` instead of the path I defined in `readinessProbe` and  `livenessProbe`. I can see in the logs that the `pod` itself checks itself easily, but the healthcheck goes ham on `/`. :( 

I've been trying for a while to find information on this topic, but I feel like it's not very well explained and documented. If anyone finds a solution for this it would be _much_ appreciated!

**Comment by matti** [comment]
@Gogoro thanks, opened a new issue because this issue is for semantic discussion

**Comment by nicksardo** [comment]
Healthcheck configuration should be provided via BackendConfig CRD and the readiness probe approach should be deprecated and eventually removed.

**Comment by nieldw** [comment]
A motivation for why option 1 (via BackendConfig CRD as @nicksardo said) is desirable is that sometimes the rules for readiness are different for serving public traffic (via an ingress) and internal traffic from other microservices. As an example, I have a service that needs to accept incoming UDP traffic before it is ready to serve public traffic. This means the `readinessProbe` on the pod must be OK but the backend for the ingress must still reflect "Unhealthy".

**Comment by Joseph-Irving** [comment]
Has there been any movement on this issue? The backend config approach seems like a reasonable solution to me. 

We're currently trying to use the readiness probe approach, however I noticed it sets the health check path for all backend services to be the readiness path including the default-http-backend, this results in the default-http-backend being marked as unhealthy as it responds with a 404 on the health check path we're using. Does anyone know if this is expected behaviour?

**Comment by DanielJoyce** [comment]
Bitten by this as well. The readiness probe scanning seems to have too many caveats to even be useful. We just manually patch the healthcheck with the CLI. :P

**Comment by cemo** [comment]
Another victim is here :( How this supposed to be configured correctly? I tried `readinessProbe` but still not working. Any workaround?

**Comment by rmtmckenzie** [comment]
@cemo Just to confirm, you've put something like this in your deployment spec:

```
    spec:
      containers:
        ports:
        - containerPort: 8080
        ...
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 6
          timeoutSeconds: 1
```

I've done that and my health checks seem to be set up for /healthz. It might be worth recreating the ingress if you're able to do that.

**Comment by julianvmodesto** [comment]
It seems that configuring the health check configuration in the Backend Config CRD is the path forward.

Is there a way to watch progress for that change to Backend Config?

Does that mean that making the 3rd option below is the compatible way forward and is a change that would be acceptable today?

> 3\. Only setup default healthcheck for ingresses. Ingress controller will only ensure the healthcheck exist periodically, but do not care about its detail configuration. User can configure it directly thru the cloud provider.

**Comment by rramkumar1** [comment]
@julianvmodesto Will ping here once work for this starts on our end.

**Comment by cemo** [comment]
@rmtmckenzie thanks. I have tried with simple example it worked. However I have used something more complicated and hit one of the limitations at here: 

```
The pod's containerPort field must be defined
The service's targetPort field must point to the pod port's containerPort value or name. Note that the targetPort defaults to the port value if not defined
The pods must exist at the time of ingress creation
The readiness probe must be exposed on the port matching the servicePort specified in the Ingress
The readiness probe cannot have special requirements like headers
The probe timeouts are translated to GCE health check timeouts
```

**Comment by linydquantil** [comment]
+1

**Comment by jgirdner** [comment]
Does anyone have a solution here? My health check is checking over HTTP and my NodePort is TCP. The health check keeps failing.

**Comment by jgirdner** [comment]
Ok found my work around. We use Django for our API and the ALLOWED_HOSTS setting was causing the API to throw an error causing the API to fail the health check. We built a custom middleware to allow the CDIR IP range of our cluster.

**Comment by PassKit** [comment]
Giving this issue a nudge with regard to https://github.com/kubernetes/ingress-gce/issues/553 and the lack of support for mTLS on the load balancer.  The lack of being able to override or remove the default load balancer health check makes it impossible to run a gRPC service with mTLS on GKE.

**Comment by mofirouz** [comment]
Yes please - this is a real pain for gRPC users. Pretty much the last remaining item to enable us to use L7 LB with gRPC backend.

**Comment by kvudata** [comment]
To add another use case/scenario where more advanced health check configuration would be helpful:

I'm setting up an HTTPS application on Istio to be exposed via IAP. Istio's gateway (a proxy which routes external traffic to applications within the Istio service mesh) by default uses a TCP load balancer but IAP requires an HTTP(s) load balancer. Thus I expose the gateway as a NodePort service which is exposing my HTTPS application on an HTTPS port, and an Ingress (using ingress-gce) pointing to the Istio gateway's HTTPS service port.

The GCE Ingress currently configures its health check to hit `/` (and defaults host header to the IP address) on the Istio gateway's HTTPS service port, but this will fail because Istio routes by the host name and a random IP address has no route. I've managed to fix this by manually configuring the health check to specify the hostname of my application via the "Host HTTP header" option on a health check (thus the health check will be routed by Istio to my application and a successful status code can be returned). Ideally one would instead be able to:
* customize the health check to reuse the Istio gateway's readiness probe (which uses a separate port) OR
* customize the health check in k8s (via the BackendConfig?) to specify the host header

**Comment by dmarkwat** [comment]
@rramkumar1 what is the change of plan you referred to in https://github.com/kubernetes/ingress-gce/pull/681? I'm very curious because what you wrote there would solve the problems I experienced very recently.

**Comment by tuananhnguyen-ct** [comment]
> To add another use case/scenario where more advanced health check configuration would be helpful:
> 
> I'm setting up an HTTPS application on Istio to be exposed via IAP. Istio's gateway (a proxy which routes external traffic to applications within the Istio service mesh) by default uses a TCP load balancer but IAP requires an HTTP(s) load balancer. Thus I expose the gateway as a NodePort service which is exposing my HTTPS application on an HTTPS port, and an Ingress (using ingress-gce) pointing to the Istio gateway's HTTPS service port.
> 
> The GCE Ingress currently configures its health check to hit `/` (and defaults host header to the IP address) on the Istio gateway's HTTPS service port, but this will fail because Istio routes by the host name and a random IP address has no route. I've managed to fix this by manually configuring the health check to specify the hostname of my application via the "Host HTTP header" option on a health check (thus the health check will be routed by Istio to my application and a successful status code can be returned). Ideally one would instead be able to:
> 
>     * customize the health check to reuse the Istio gateway's readiness probe (which uses a separate port) OR
> 
>     * customize the health check in k8s (via the BackendConfig?) to specify the host header

We used a rewrite for default host on Istio (anything without a valid host hitting /) to Istio healthcheck endpoint (/healthz/ready), so the fix in on Istio instead of the healthcheck.

**Comment by hmeerlo** [comment]
This issue is now open for more than 2 years and still we can not customise the health checks. For me it makes it impossible to use certain k8s deployments on GKE. Is there any progress at all on this issue?

Just for reference, my problem: I have a GKE cluster in which I deploy a stable/wordpress helm chart. Certificate is managed by cert-manager and GCLB is created and which terminates the HTTPS (so far so good). But the health checks keep failing because the wordpress backend (rightfully) requires all requests to be over https so it returns a 301 instead of the much needed 200. I tried doing health check over https but it refuses to do that. I tried adding a 'x-forwarded-proto: https' header but it refuses that as well. We need a way to have more control over this!

**Comment by bowei** [comment]
We will pick this up into backendconfig, likely in the next release.

**Comment by lfaoro** [comment]
@bowei 
> On the other side, each application may want to handle healthcheck differently. To bypass this limitation, on Ingress creation, ingress controller will scan all backend pods and pick the first ReadinessProbe it encounters and configure healthcheck accordingly. 

This means that if my pod has the following config:
```yaml
          readinessProbe:
            httpGet:
              path: /v1/card/health
              port: http
              httpHeaders:
                  - name: Authorization
                    value: "Bearer health-check"
```
the LB health-check should successfully authenticate and mark it HEALTHY.

Instead I see the LB configured the HC on Path `/` expecting a 200 from there.

**Comment by rib** [comment]
Is there any kind of workaround for this issue to allow exposing a grpc service via Ingress?

This issue is getting pretty old so there's no indication it's going to get addressed any time soon, but does that really mean no one is successully able to host a GRPC service on GKE via Ingress? Surely not?

Is the only workaround perhaps to configure a load balancer manually without creating a GKE Ingress resource?

Initially I tried making my server host a `http://:8080/readiness` separate from my grpc service on port 8443 but found Ingress couldn't be coerced into using that.

Then I tried configuring a readinessProbe using `tcpSocket` to at least avoid the separate port, before realising the Ingress controller also doesn't understand that.

It seems that there's no way to configure a readinessProbe to use `http/2` (in particular without TLS, since TLS will be terminated by Ingress) so now I'm somewhat at a loss as to what to do next, until this issue is resolved - but this issue is over two years old now :(

Any pointer for a workaround would be hugely appreciated!

**Comment by rib** [comment]
Ok, so after a some more head scratching I did actually get my grpc service working with Ingress.

There were several issues compounding for me since I hadn't fully appreciated that the https load balancer (and health checks) created by the Ingress will only connect to a http/2 backend service with TLS. I had been disabling TLS since I assumed it would be terminated by the load balancer and I didn't understand why my server was always marked as unhealthy. I think I was half expecting that there would be some place to configure certificates if this were the case but it turns out they connect fine with unverified, self-signed certificates - using an IP subjectAltName.

_Luckily_ the grpc server implementation I'm using [(tonic)](https://github.com/hyperium/tonic) does actually return a status 200 for any uri that doesn't match a grpc request. Things would get a bit more complicated if I needed to change the health check path, since tonic doesn't allow http 1 connections so the trick of configuring a `httpGet` `readinessProbe`  (currently I use a `tcpSocket` probe) would require modifying tonic.

**Comment by omatsko** [comment]
Is there any ETA on this issue?

Also, do I understand it correctly, health checks for ingress-gce (global load balancer) are configured automatically right now? Because if I change those configs after deploying, my changes are reverted.

And with this feature, I would be able to configure path/port/host from within my GKE deployment?

**Comment by jerome-arzel** [comment]
Hello,

You Can close this issue, it is now resolved.
Thanks

Regards

**Comment by mofirouz** [comment]
@jerome-arzel Can you point me to documentation and/or changelog that mentions how to configure healthcheck if this is resolved? I don't see anything in v1.8.0.

**Comment by rramkumar1** [comment]
@mofirouz This is not resolved yet. I'm not sure what the previous comment was referring to.

**Comment by omatsko** [comment]
So... Any ETAs?

**Comment by matti** [comment]
peronally I stopped believing in gce ingress and just created LoadBalancer+ingress-nginx. the only downsides: a) can not use global ips b) have to run ingress-nginx as well.

**Comment by rramkumar1** [comment]
@omatsko Unfortunately this work got sidetracked in favor of other work but we have picked it back up and are actively working on it. See https://github.com/kubernetes/ingress-gce/pull/1010

**Comment by soichisumi** [comment]
Can HealthCheckConfig (implemented in [this PR](https://github.com/kubernetes/ingress-gce/pull/1010)) configure L7LB to pass health checks for grpc applications?

**Comment by bowei** [comment]
Hi everyone, please take a look at https://github.com/kubernetes/ingress-gce/pull/1029 which implements the healthchecking overrides on the backendconfig for a service.

**Comment by mofirouz** [comment]
@bowei thanks a lot for your PR. I think this should work well with gRPC applications since we can use a custom path for Healthchecks.

Can you tell us what versions of GKE will this addition be available to use with?

**Comment by naseemkullah** [comment]
> Hi everyone, please take a look at #1029 which implements the healthchecking overrides on the backendconfig for a service.

Thanks @bowei ! But are GCE-Ingress health check overrides available today ?  Not seeing any related docs in https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

How to keep track if it is available in a given version of GKE (e.g. stable channel) ?

**Comment by dustinmoris** [comment]
Can someone post here what the recommended fix is? What does a BackendConfig with a health check look like? What is the min Kubernetes version where this feature is supported?

**Comment by bowei** [comment]
the docs will be updated very soon -- @spencerhance

**Comment by jbg** [comment]
An example BackendConfig using this feature:

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backend-config
spec:
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: TCP
    # defaults to serving port
    # port:
    # only for HTTP/HTTPS type
    # path:
```

ref: https://godoc.org/k8s.io/ingress-gce/pkg/apis/backendconfig/v1#HealthCheckConfig

It doesn't appear to work though (health check is still created as type HTTP and path "/" regardless of what I configure in the BackendConfig). Is there any GKE release that supports this yet?

**Comment by mofirouz** [comment]
I've tried the following setup with no success sadly:

My app ([nakama](https://github.com/heroiclabs/nakama)) exposes two ports - 7110 for gRPC (HTTP/2) and 7111 for gRPC-gateway (HTTP 1.1 with `/` used for LB healthchecks).

This is running on a GKE instance version 1.16.8-gke.10.

```yml
kind: Service
apiVersion: v1
metadata:
  name: nakama3
  namespace: heroiclabs
  labels:
    project: heroiclabs
  annotations:
    cloud.google.com/app-protocols: '{"nakama-api":"HTTP","nakama-grpc-api":"HTTP2"}'
    beta.cloud.google.com/backend-config: >-
      {"ports":{"nakama-api":"backendconfig","nakama-grpc-api":"backendconfig"}, "default": "backendconfig"}
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - name: nakama-grpc-api
      protocol: TCP
      port: 7110
      targetPort: 7110
    - name: nakama-api
      protocol: TCP
      port: 7111
      targetPort: 7111
  selector:
    app: nakama
  type: NodePort
```

---

backendconfig.yml

```yml
kind: BackendConfig
apiVersion: cloud.google.com/v1
metadata:
  labels:
    project: heroiclabs
  name: backendconfig
  namespace: heroiclabs
spec:
  connectionDraining:
    drainingTimeoutSec: 5
  logging:
    sampleRate: 0.0
  timeoutSec: 86400
  healthCheck:
    port: 7111
    checkIntervalSec: 10
```

---

ingress.yml

```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gundam3
  namespace: heroiclabs
  labels:
    project: heroiclabs
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: heroiclabs
    kubernetes.io/ingress.allow-http: 'false'
spec:
  backend:
    serviceName: gundam3
    servicePort: 7110
```

---

The result is the following:

<img width="1119" alt="lb1" src="https://user-images.githubusercontent.com/137265/84936822-bc7ab300-b0d2-11ea-94f2-cccda5596ad1.png">
<img width="535" alt="lb2" src="https://user-images.githubusercontent.com/137265/84936824-bdabe000-b0d2-11ea-9324-c80e49d1f33c.png">

---

Apologies for tagging you individually guys, but @bowei or @rramkumar1 can you shed some light on what might be going wrong here?

**Comment by bowei** [comment]
cc: @spencerhance

**Comment by spencerhance** [comment]
This feature has not rollout out yet, but will be available in the next release (1.17.6-gke.7) next week, which the exception of port configuration.  That will require a bug fix that should roll out a few weeks after.  Additionally, this feature won't be available in 1.16 clusters until about a month after it has been released in 1.17.

**Comment by mofirouz** [comment]
Thanks @spencerhance and @bowei for the prompt response - I'll keep a look out for that.

**Comment by ahmetgeymen** [comment]
```
...
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 9090
  initialDelaySeconds: 5
...
```

I can manage to have healthy ingress for around 10 minutes by giving custom health check (with node port assigned with readinessProbe port) for automatically created backend service config for load balancer created with ingress. After about 10 minutes health check returns to look for default node port and then I get 502 again for external ip.

(Using screenshot of @mofirouz, but the same config field I mention below.)

<img width="535" alt="84936824-bdabe000-b0d2-11ea-9324-c80e49d1f33c" src="https://user-images.githubusercontent.com/3007479/85077569-4b6af680-b1cb-11ea-8d67-d2a3f412e137.png">

[https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#ingress_for_external_and_internal_traffic](url)

Unfortunately they warn about not to update load balancer config manually. But without doing anything manually, I can not reach my service from assigned ip of the load balancer. By the way, I didn't try updating the actuator's health endpoint to `/` yet.

**Comment by bowei** [comment]
@ahmetgeymen  -- hopefully after the healthcheck feature is available, the need to edit the healthcheck settings manually will go away. Let us know if there is anything that remains that makes custom configuration necessary..

**Comment by Gatsby-Lee** [comment]
This  seems available on beta. I am on 1.17.6-gke.11.

I don't need change in Ingress.

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: apimars-prod
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 3
    requestPath: /healthz
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-healthz
  namespace: apimars-prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-healthz
  type: NodePort
```

**Comment by gnarea** [comment]
I'm using v1.17.6-gke.7 but can't get this to work with gRPC. I basically want to use *TCP* (not HTTP2) health checks because those HTTP2 health checks don't work at all with gRPC.

Here's the resources I have:

```
$ kubectl get svc gw-test-relaynet-internet-gateway-cogrpc -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports":{"grpc":"cogrpc"}, "default":
      "cogrpc"}'
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"8081":"k8s1-4ddb902c-defaul-gw-test-relaynet-internet-gate-80-01fab572"},"zones":["europe-west2-a"]}'
    meta.helm.sh/release-name: gw-test
    meta.helm.sh/release-namespace: default
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
  creationTimestamp: "2020-06-29T14:21:27Z"
  labels:
    app.kubernetes.io/instance: gw-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: relaynet-internet-gateway-cogrpc
    app.kubernetes.io/version: 1.3.9
    helm.sh/chart: relaynet-internet-gateway-0.1.0
  name: gw-test-relaynet-internet-gateway-cogrpc
  namespace: default
  resourceVersion: "606508"
  selfLink: /api/v1/namespaces/default/services/gw-test-relaynet-internet-gateway-cogrpc
  uid: 9e28d795-f1ee-49ab-a307-1424b016d46a
spec:
  clusterIP: 10.16.5.230
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    nodePort: 32112
    port: 8081
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/instance: gw-test
    app.kubernetes.io/name: relaynet-internet-gateway-cogrpc
  sessionAffinity: None
  type: NodePort

$ kubectl get backendconfig cogrpc -o yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
  creationTimestamp: "2020-06-30T16:50:36Z"
  generation: 2
  labels:
    project: public-gw
  name: cogrpc
  namespace: default
  resourceVersion: "608964"
  selfLink: /apis/cloud.google.com/v1/namespaces/default/backendconfigs/cogrpc
  uid: 9387cc5d-6710-4c7e-99ed-dc78f124da5f
spec:
  healthCheck:
    checkIntervalSec: 20
    healthyThreshold: 1
    port: 8081
    timeoutSec: 1
    type: TCP
    unhealthyThreshold: 3
```

The old HTTP2 healthcheck is still used. In fact, I can't see the healthcheck that should've been created by the `BackendConfig` above (which, according to `kubectl`, is in the right cluster and namespace) -- I can see it in k8s but not GCP (I'm sure the `project` label is set to the right value).

Any idea what I'm doing wrong?

**Comment by Gatsby-Lee** [comment]
@gnarea 
I don't know much about grpc
maybe you can get some idea from here - https://cloud.google.com/compute/docs/reference/rest/v1/healthChecks

**Comment by gnarea** [comment]
Thanks @Gatsby-Lee! I think that link helps with the structure of the data of the `.spec`, but I don't think that's the problem here. The values I specified are valid and seem to be honoured according to `kubectl describe backendconfig cogrpc`. The problem is that the LB isn't using my custom health check -- And in fact, I can't find that healthcheck on GCP, but I can still see my `BackendConfig` resource in the cluster, which I guess is why the LB can't use it.

I also gave up on the TCP probe because I couldn't get it to work and, even if I eventually did, it'd be far too unreliable for a health check. Instead, per the suggestion of a GCP support agent, I've now created a new container in the pod, which is an HTTP app with a single endpoint that in turn pings my gRPC service using the gRPC health check protocol. This approach is basically Option 3 in https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/

To sum up, I want to configure the gRPC backend in the LB in such a way that the health check points to the HTTP proxy containers but the actual backend uses the gRPC containers. This is the kind of things you'd be able to do with the fix in this issue, right? If so, how can I configure the `BackendConfig`, `Service` and potentially `Ingress` to achieve this?

Here's my current service and backendconfig in case that's useful:

```
$ kubectl get svc gw-test-relaynet-internet-gateway-cogrpc -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"8081":"k8s1-4ddb902c-defaul-gw-test-relaynet-internet-gate-80-01fab572"},"zones":["europe-west2-a"]}'
    meta.helm.sh/release-name: gw-test
    meta.helm.sh/release-namespace: default
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
  creationTimestamp: "2020-06-29T14:21:27Z"
  labels:
    app.kubernetes.io/instance: gw-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: relaynet-internet-gateway-cogrpc
    app.kubernetes.io/version: 1.3.10
    helm.sh/chart: relaynet-internet-gateway-0.1.0
  name: gw-test-relaynet-internet-gateway-cogrpc
  namespace: default
  resourceVersion: "989264"
  selfLink: /api/v1/namespaces/default/services/gw-test-relaynet-internet-gateway-cogrpc
  uid: 9e28d795-f1ee-49ab-a307-1424b016d46a
spec:
  clusterIP: 10.16.5.230
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    nodePort: 32112
    port: 8081
    protocol: TCP
    targetPort: grpc
  - name: health-check
    nodePort: 32758
    port: 8082
    protocol: TCP
    targetPort: health-check
  selector:
    app.kubernetes.io/instance: gw-test
    app.kubernetes.io/name: relaynet-internet-gateway-cogrpc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

$ kubectl get backendconfig cogrpc -o yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
  creationTimestamp: "2020-07-01T10:41:21Z"
  generation: 1
  labels:
    project: public-gw
  name: cogrpc
  namespace: default
  resourceVersion: "1026811"
  selfLink: /apis/cloud.google.com/v1/namespaces/default/backendconfigs/cogrpc
  uid: 57c6219f-91ee-4e45-9576-a817c958dc3c
spec:
  healthCheck:
    checkIntervalSec: 20
    healthyThreshold: 1
    port: 8082
    timeoutSec: 1
    type: HTTP
    unhealthyThreshold: 3
```

**Comment by Gatsby-Lee** [comment]
I was wrong. I don't think setting healthcheck through Backendconfig works.
Ingress can use custom healthcheck only if Service exists before Ingress knows about the Service.

And, even if custom healthcheck works by bringing up Ingress after Service,
the custom healthcheck won't work if new Pod is deployed.

This is what @nicksardo explained before in different msg thread.

BTW, ingress doesn't have to be removed to use custom healthcheck.
if Service info is removed from Ingress and added back again, then Ingress uses custom healthcheck again.
(But, we can't do this on prod) lol

**Comment by dpkirchner** [comment]
> This feature has not rollout out yet, but will be available in the next release (1.17.6-gke.7) next week, which the exception of port configuration. That will require a bug fix that should roll out a few weeks after. Additionally, this feature won't be available in 1.16 clusters until about a month after it has been released in 1.17.

May I suggest/request adding this to the Feature Comparison table at https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features ? I see custom health checks are marked as being in beta (for Internal Ingress[1]), but there's no version number so it's not clear how to "activate" the beta feature.

[1] I assume this includes ingresses used for IAP given the healthCheck attribute doesn't have an effect in BackendConfigs used there.

**Comment by christopherdbull** [comment]
Is there any reason why we can't set the Host header with the BackendConfig CRD?

**Comment by lelandhwu** [comment]
Hey guys, 

Currently I have a service that publishes port `12345` as the service port. I want this to be the port that Ingress routes traffic to because it's the port that listens to websocket messages. I'm making a game by the way, if this adds some color

The Ingress controller looks like this:

```
spec:
  defaultBackend:
    service:
      name: other-backend-service
      port:
        number: 7350
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-server-service
            port:
              number: 12345
        path: /my-server
        pathType: ImplementationSpecific
```

The service listens to websocket connections on port 12345, but I've also spun up a small python server that runs in the same pod experimentally just for the sole purpose of passing the health check. It listens to http requests on `/` port `80`, and return `200 OK`. I've gotten it to pass the health check, but only when I publish this port as the service port. When I do this, traffic fails to route to the other port listening for websocket traffic, as they are on the same path

Is there a way for me to configure the health check so that it checks against port 80 without having to publish it as the service port on the same path as the port I want to route traffic to?

I really want to stay in the GCE ingress ecosystem so I would love to get this to work if possible.
Thank you so much

**Comment by swetharepakula** [comment]
@lelandhwu , can you please create a new issue with the same content as https://github.com/kubernetes/ingress-gce/issues/42#issuecomment-1064416269. This seems like a separate issue from Healthcheck configuration.


The remaining ask on this issue is to add Host Header to the BackendConfig. Please open a different issue if this FR is still desired. 

Since this issue is specific to custom healthchecks we are closing it out. Custom healthchecks are configurable through the BackendConfig CRD: https://github.com/kubernetes/ingress-gce/issues/42#issuecomment-1064416269.
